Test: Add trap … ERR for better error reporting

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -1,5 +1,8 @@
 #!/usr/bin/env bash
 set -Eeuo pipefail
+trap 'ec=$?; echo 1>&2 "ERROR: ec=$ec line=$LINENO file=$0"
+             echo 1>&2 "      cmd=$BASH_COMMAND";
+             exit $ec;' ERR
 
 PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
 
