Test,build-files: Clean up build in several ways
1. We now have a build-files/ subdir for files that we need to copy
   into build directories. Gitignore files here (to make them more
   obvious and avoid Git actually using them) are named PROG.gitignore;
   these are copied to `.gitignore` in the build dirs. Other files (in
   subdirs `PROG/`) are copied directly or will be as they appear.

2. We now don't try to install system deps if we haven't found any
   that we need. If we do need to install some, we print message
   explaining what we're installing. (We do not use `apt install -y`
   so that at this point the user can choose to abort.)

3. Add the autoconf package, as this is needed by Bash 3.x.

4. We copy the binaries into bin/, instead of linking them, so that
   they're easier to copy out (you won't accidentally copy links).
   That will also leave the old build in place should a new version
   fail to build, once we have better error checking on our builds.

5. Tests are now at the very end of the build_*() functions, and are
   run on the bin/ version rather than a build product in the build
   dir.

6. Various other minor bits of cleanup and clarification.

diff --git a/Test b/Test
--- a/Test
+++ b/Test
@@ -2,7 +2,6 @@
 set -Eeuo pipefail
 
 PROJDIR=$(cd "$(dirname "$0")" && pwd -P)
-cd "$PROJDIR"
 
 die()       { local ec="$1"; shift; echo 1>&2 "$@"; exit "$ec"; }
 test_dep()  { "$@" >/dev/null 2>&1; }
@@ -15,79 +14,44 @@ deps_debian() {
     test_dep make --version         || deps+=(make)
 
     #   bash 3
+    test_dep autoconf --version     || deps+=(autoconf)
     test_dep yacc --version         || deps+=(bison)
 
-    [[ -n ${deps[@]} ]]             && sudo apt-get install "${deps[@]}"
-    true
+    [[ ${#deps[@]} -eq 0 ]] && return 0     # no installs necessary
+
+    echo '===== Installing missing system build dependnecies:'
+    echo "      ${deps[@]}"
+    sudo apt-get install "${deps[@]}"
 }
 
-BASH3_GITIGNORE='
-/.gitignore
-
-/.build
-/.made
-/Makefile
-/bash
-/bashbug
-/bashversion
-/builtins/Makefile
-/builtins/builtext.h
-/builtins/builtins.c
-/builtins/mkbuiltins
-/builtins/pipesize.h
-/builtins/psize.aux
-/config.h
-/config.log
-/config.status
-/doc/Makefile
-/examples/loadables/Makefile
-/examples/loadables/perl/Makefile
-/lib/glob/Makefile
-/lib/intl/Makefile
-/lib/malloc/Makefile
-/lib/readline/Makefile
-/lib/sh/Makefile
-/lib/termcap/Makefile
-/lib/tilde/Makefile
-/lsignames.h
-/mksignames
-/mksyntax
-/pathnames.h
-/po/Makefile
-/po/Makefile.in
-/po/POTFILES
-/signames.h
-/stamp-h
-/support/Makefile
-/syntax.c
-/version.h
-
-*.o
-*.a
-'
-
-#   These committed files are changed because we force a parser rebuild
-#   (the y.tab.* committed in the repo are buggy). To avoid annoying
-#   messages from `git status` we mark them to be assumed unchanged.
-BASH3_ASSUME_UNCHANGED=( parser-built y.tab.c y.tab.h)
-
 build_bash3() {
+    #   These committed files are changed because we force a parser rebuild
+    #   (the y.tab.* committed in the repo are buggy). To avoid annoying
+    #   messages from `git status` we mark them to be assumed unchanged.
+    BASH3_ASSUME_UNCHANGED=( parser-built y.tab.c y.tab.h)
+
     [[ -e bash3/parse.y ]] || {
         git submodule update --init bash3
         touch bash3/parse.y      # shipped y.tab.* are buggy; regenerate
-        echo "$BASH3_GITIGNORE" > bash3/.gitignore
     }
+    cp build-files/bash3.gitignore bash3/.gitignore
     (
         cd bash3
         [[ -e config.h ]] || ./configure
         make -j16
         git update-index --assume-unchanged "${BASH3_ASSUME_UNCHANGED[@]}"
-        ./bash --version
-        [[ $(./bash --version) == *3.2.48* ]] || die 2 "Bad bash3 version?"
     )
-    rm -f bin/bash3 && ln -s ../bash3/bash bin/bash3
+    cp bash3/bash bin/bash3
+
+    bin/bash3 --version
+    [[ $(bin/bash3 --version) == *3.2.48* ]] || die 2 "Bad bash3 version?"
 }
 
+####################################################################
+#   Main
+
 deps_debian     # XXX should support other systems?
-mkdir -p bin/
+
+cd "$PROJDIR"
+rm -rf bin/ && mkdir bin/
 build_bash3
